name = "ujang" # todo
main = "_worker.js"
compatibility_date = "2024-05-26"

[[routes]]
pattern = "budakbaong.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.budakbaong.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.budakbaong.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.budakbaong.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.vcip.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.budakbaong.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.budakbaong.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.budakbaong.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.budakbaong.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.budakbaong.my.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.budakbaong.my.id"
custom_domain = true
[[routes]]
pattern = "business.blibli.com.budakbaong.my.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.budakbaong.my.id"
custom_domain = true

